# Solution

In [1]:
import torch
import torch.nn as nn

### Make a LSTM module
* input size:  4
* hidden size:  2  
* number of layers: 3

In [2]:
mod = nn.LSTM(4,2, num_layers=3, bias=False)
print(mod)

LSTM(4, 2, num_layers=3, bias=False)


### Print weight_ih from layer 0, 1 and 2 (before to do it ask yourself what will be the size)

In [3]:
print(mod.weight_ih_l0)

Parameter containing:
tensor([[ 0.6810,  0.1597, -0.4753,  0.6480],
        [ 0.3999,  0.0845, -0.1915, -0.1690],
        [-0.1068, -0.5661, -0.6647, -0.0684],
        [ 0.0035,  0.0086,  0.3618, -0.5600],
        [-0.1475,  0.2888, -0.0100, -0.1515],
        [-0.6326,  0.4274, -0.7024,  0.3786],
        [ 0.3331, -0.0639, -0.3803, -0.1814],
        [ 0.5822, -0.1142, -0.6537,  0.4741]], requires_grad=True)


In [4]:
print(mod.weight_ih_l1)

Parameter containing:
tensor([[ 0.2403, -0.2977],
        [ 0.3457,  0.1963],
        [ 0.3197, -0.5851],
        [-0.5602, -0.5779],
        [ 0.0531,  0.4353],
        [-0.5108, -0.3760],
        [ 0.2038, -0.6399],
        [ 0.6484, -0.2659]], requires_grad=True)


In [5]:
print(mod.weight_ih_l2)

Parameter containing:
tensor([[-0.6126, -0.3906],
        [-0.2286, -0.6504],
        [ 0.5544,  0.5939],
        [ 0.6307,  0.1669],
        [-0.2800,  0.1384],
        [-0.2687, -0.3656],
        [-0.2257,  0.2897],
        [-0.1148,  0.2490]], requires_grad=True)


### Print weight_hh from layer 0, 1 and 2 (before to do it ask yourself what will be the size)

In [6]:
print(mod.weight_hh_l0)
print(mod.weight_hh_l1)
print(mod.weight_hh_l2)

Parameter containing:
tensor([[-0.1176, -0.0421],
        [ 0.2910,  0.0622],
        [-0.3460, -0.0967],
        [ 0.1649,  0.4669],
        [ 0.0860, -0.4596],
        [-0.2235,  0.6167],
        [-0.4651,  0.3319],
        [-0.2829,  0.5531]], requires_grad=True)
Parameter containing:
tensor([[ 0.0272,  0.6871],
        [-0.6316, -0.1380],
        [-0.1398, -0.3466],
        [-0.2079, -0.2171],
        [-0.6483,  0.2084],
        [-0.1247,  0.2557],
        [-0.3080, -0.4360],
        [-0.0921, -0.2234]], requires_grad=True)
Parameter containing:
tensor([[ 0.5408,  0.0462],
        [ 0.4705,  0.1985],
        [ 0.2371, -0.5406],
        [-0.4348,  0.4579],
        [ 0.6672, -0.1096],
        [ 0.4246, -0.3878],
        [ 0.5296,  0.1628],
        [-0.1355,  0.2892]], requires_grad=True)


### Create a sequence to be processed by the RNN:
$$
x_1 = \begin{bmatrix}
0\\1\\ 0\\0
\end{bmatrix}
\qquad
x_2 = \begin{bmatrix}
0\\0\\0\\ 1
\end{bmatrix}
\qquad
x_3 = \begin{bmatrix}
 1\\0\\0\\0
\end{bmatrix}
\qquad
x_4 = \begin{bmatrix}
 1\\0\\0\\0
\end{bmatrix}
\qquad
x_5 = \begin{bmatrix}
 1\\0\\0\\0
\end{bmatrix}
$$

In [7]:
x1=torch.Tensor([0,1,0,0])
x2=torch.Tensor([0,0,0,1])
x3=torch.Tensor([1,0,0,0])
x4=torch.Tensor([1,0,0,0])
x5=torch.Tensor([1,0,0,0])

### Put the squence in a tensor of appropriate shape:  seq_len x bs x input_size:

In [8]:
input_seq = torch.stack( (x1,x2,x3,x4,x5) , dim=0) 

In [9]:
print(input_seq)
print(input_seq.size())

tensor([[0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.]])
torch.Size([5, 4])


In [10]:
bs=1
input_seq = input_seq.view(5,bs,4)

In [11]:
print(input_seq.size())

torch.Size([5, 1, 4])


### Feed the sequence to the rnn

In [12]:

output_seq, (h_last,c_last) = mod( input_seq )


### Print the last hidden state and the last memory cell and ask yourself if this is the expected dimension 

In [13]:
h_last

tensor([[[-0.0582, -0.3199]],

        [[-0.0506,  0.0615]],

        [[ 0.0077, -0.0025]]], grad_fn=<ViewBackward>)

In [14]:
c_last

tensor([[[-0.1020, -0.5765]],

        [[-0.0929,  0.1211]],

        [[ 0.0152, -0.0049]]], grad_fn=<ViewBackward>)

### Print the hidden states from the last layer and ask yourself if it is the correct dimension

In [15]:
output_seq

tensor([[[-0.0014,  0.0010]],

        [[-0.0030,  0.0011]],

        [[-0.0013, -0.0001]],

        [[ 0.0028, -0.0015]],

        [[ 0.0077, -0.0025]]], grad_fn=<CatBackward>)