In [17]:
import pandas as pd
import arff
import numpy as np
import scipy as sp
import pandas as pd
import sklearn
import torch

In [18]:
data = pd.read_csv('tao-cleaned.csv', sep=",")
del data['Unnamed: 0']
data.head()

Year  Month  Day  Latitude  Longitude  Zonal_Winds  Meridional_Winds  \
0    80      3    7     -0.02    -109.46         -6.8               0.7   
1    80      3    8     -0.02    -109.46         -4.9               1.1   
2    80      3    9     -0.02    -109.46         -4.5               2.2   
3    80      3   10     -0.02    -109.46         -3.8               1.9   
4    80      3   11     -0.02    -109.46         -4.2               1.5   

    Humidity  Air_Temp  Sea_Surface_Temp  
0  81.236525     26.14             26.24  
1  81.236525     25.66             25.97  
2  81.236525     25.69             25.28  
3  81.236525     25.57             24.31  
4  81.236525     25.30             23.19

In [19]:
labels = data['Sea_Surface_Temp']
labels.head()
print(len(labels))

178080


In [20]:
data.head()

Year  Month  Day  Latitude  Longitude  Zonal_Winds  Meridional_Winds  \
0    80      3    7     -0.02    -109.46         -6.8               0.7   
1    80      3    8     -0.02    -109.46         -4.9               1.1   
2    80      3    9     -0.02    -109.46         -4.5               2.2   
3    80      3   10     -0.02    -109.46         -3.8               1.9   
4    80      3   11     -0.02    -109.46         -4.2               1.5   

    Humidity  Air_Temp  Sea_Surface_Temp  
0  81.236525     26.14             26.24  
1  81.236525     25.66             25.97  
2  81.236525     25.69             25.28  
3  81.236525     25.57             24.31  
4  81.236525     25.30             23.19

In [26]:
train_data = data[:124656]
test_data = data[124656:]
train_data.head()

Year  Month  Day  Latitude  Longitude  Zonal_Winds  Meridional_Winds  \
0    80      3    7     -0.02    -109.46         -6.8               0.7   
1    80      3    8     -0.02    -109.46         -4.9               1.1   
2    80      3    9     -0.02    -109.46         -4.5               2.2   
3    80      3   10     -0.02    -109.46         -3.8               1.9   
4    80      3   11     -0.02    -109.46         -4.2               1.5   

    Humidity  Air_Temp  Sea_Surface_Temp  
0  81.236525     26.14             26.24  
1  81.236525     25.66             25.97  
2  81.236525     25.69             25.28  
3  81.236525     25.57             24.31  
4  81.236525     25.30             23.19

In [27]:
test_data.head()

Year  Month  Day  Latitude  Longitude  Zonal_Winds  Meridional_Winds  \
124656    93      5   21     -5.03     -124.9         -7.6              -1.1   
124657    93      5   22     -5.03     -124.9         -6.7              -0.2   
124658    93      5   23     -5.03     -124.9         -7.5               0.8   
124659    93      5   24     -5.03     -124.9         -6.1              -1.5   
124660    93      5   25     -5.03     -124.9         -5.1              -1.5   

        Humidity  Air_Temp  Sea_Surface_Temp  
124656      84.0     27.54             28.41  
124657      82.4     27.70             28.38  
124658      81.3     28.05             28.39  
124659      78.5     27.81             28.41  
124660      84.0     27.62             28.36

In [29]:
train_label = labels[:124656]
test_label = labels[124656:]

train_label.head()

0    26.24
1    25.97
2    25.28
3    24.31
4    23.19
Name: Sea_Surface_Temp, dtype: float64

In [30]:
test_label.head()

124656    28.41
124657    28.38
124658    28.39
124659    28.41
124660    28.36
Name: Sea_Surface_Temp, dtype: float64

In [37]:
torch_tensor_train_data = torch.tensor(train_data.values)
torch_tensor_test_data = torch.tensor(test_data.values)
print('Train data tensor:')
print('\n')
print(torch_tensor_train_data)
print('\n')
print('Test data tensor:')
print('\n')
print(torch_tensor_test_data)

Train data tensor:


tensor([[80.0000,  3.0000,  7.0000,  ..., 81.2365, 26.1400, 26.2400],
        [80.0000,  3.0000,  8.0000,  ..., 81.2365, 25.6600, 25.9700],
        [80.0000,  3.0000,  9.0000,  ..., 81.2365, 25.6900, 25.2800],
        ...,
        [93.0000,  5.0000, 18.0000,  ..., 82.8000, 28.0500, 28.4300],
        [93.0000,  5.0000, 19.0000,  ..., 83.6000, 28.0500, 28.4000],
        [93.0000,  5.0000, 20.0000,  ..., 80.5000, 27.7800, 28.4100]],
       dtype=torch.float64)


Test data tensor:


tensor([[93.0000,  5.0000, 21.0000,  ..., 84.0000, 27.5400, 28.4100],
        [93.0000,  5.0000, 22.0000,  ..., 82.4000, 27.7000, 28.3800],
        [93.0000,  5.0000, 23.0000,  ..., 81.3000, 28.0500, 28.3900],
        ...,
        [98.0000,  6.0000, 13.0000,  ..., 81.3000, 27.1700, 27.9300],
        [98.0000,  6.0000, 14.0000,  ..., 76.2000, 27.3600, 28.0300],
        [98.0000,  6.0000, 15.0000,  ..., 81.2365, 27.0900, 28.0900]],
       dtype=torch.float64)


In [39]:
torch_tensor_train_label = torch.tensor(train_label.values)
torch_tensor_test_label = torch.tensor(test_label.values)
print('Train label tensor:')
print('\n')
print(torch_tensor_train_label)
print('\n')
print('Test label tensor:')
print('\n')
print(torch_tensor_test_label)

Train label tensor:


tensor([26.2400, 25.9700, 25.2800,  ..., 28.4300, 28.4000, 28.4100],
       dtype=torch.float64)


Test label tensor:


tensor([28.4100, 28.3800, 28.3900,  ..., 27.9300, 28.0300, 28.0900],
       dtype=torch.float64)


In [42]:
torch.save(torch_tensor_train_data,'tao_tensors/train_data.pt')
torch.save(torch_tensor_test_data,'tao_tensors/test_data.pt')
torch.save(torch_tensor_train_label,'tao_tensors/train_label.pt')
torch.save(torch_tensor_test_label,'tao_tensors/test_label.pt')