# Solution

In [1]:
import torch
import torch.nn as nn

ModuleNotFoundError: No module named 'utils'

### Make a RNN module
* input size:  2
* hidden size:  2  
* number of layers: 1
* nonlinearity $\sigma(x) = \text{ReLU}(x)$.  To do this you do:  nonlinearity = 'relu'

In [2]:
mod = nn.RNN(2,2, num_layers=1, bias=False, nonlinearity='relu' )
print(mod)

RNN(2, 2, bias=False)


### Set the weights to be:$ \qquad 
R= \begin{bmatrix}
1 & 0 \\
0 & 1
\end{bmatrix} \qquad \text{and} \qquad 
W= \begin{bmatrix}
-2 & 0  \\
0 & 2 
\end{bmatrix} 
$

Recall the API:
* mod.weight_ih_l3   (weight of the matrix to go from input to hidden at layer 3)
* mod.weight_hh_l5   (weight of the matrix to go from hidden to hidden at layer 5)

In [3]:
R = torch.Tensor([[1,0],[0,1]])
W = torch.Tensor([[-2,0],[0,2]])

R=nn.Parameter(R)
W=nn.Parameter(W)

mod.weight_hh_l0 = R
mod.weight_ih_l0 = W

In [4]:
print(mod.weight_hh_l0)

Parameter containing:
tensor([[1., 0.],
        [0., 1.]], requires_grad=True)


In [5]:
mod.weight_ih_l0 

Parameter containing:
tensor([[-2.,  0.],
        [ 0.,  2.]], requires_grad=True)

### Create a sequence to be processed by the RNN:
$$
x_1 = \begin{bmatrix}
1\\ 0
\end{bmatrix}
\qquad
x_2 = \begin{bmatrix}
0\\ 1
\end{bmatrix}
\qquad
x_3 = \begin{bmatrix}
0\\ 1
\end{bmatrix}
$$

In [6]:
x1=torch.Tensor([1,0])
x2=torch.Tensor([0,1])
x3=torch.Tensor([0,1])

### Put the squence in a tensor of appropriate shape:  seq_len x bs x input_size:

In [7]:
input_seq = torch.stack( (x1,x2,x3) , dim=0) 

In [8]:
print(input_seq)
print(input_seq.size())

tensor([[1., 0.],
        [0., 1.],
        [0., 1.]])
torch.Size([3, 2])


In [9]:
bs=1
input_seq = input_seq.view(3,bs,2)

In [10]:
print(input_seq.size())

torch.Size([3, 1, 2])


### Feed the sequence to the rnn

In [11]:

output_seq, h_last = mod( input_seq )


### Print the last hidden state 

In [12]:
h_last

tensor([[[0., 4.]]], grad_fn=<ViewBackward>)

### Print all the hidden states

In [21]:
output_seq

tensor([[[0., 0.]],

        [[0., 2.]],

        [[0., 4.]]], grad_fn=<CatBackward>)